package igu;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jczr8
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelP1 = new javax.swing.JPanel();
        LabelDrawmon = new javax.swing.JLabel();
        JBAceptar = new javax.swing.JButton();
        TFNombre = new javax.swing.JTextField();
        LabelElegir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelP1.setBackground(new java.awt.Color(255, 255, 255));
        PanelP1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelP1.setForeground(new java.awt.Color(255, 255, 255));

        LabelDrawmon.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        LabelDrawmon.setForeground(new java.awt.Color(0, 0, 0));
        LabelDrawmon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDrawmon.setText("Drawmon");

        JBAceptar.setBackground(new java.awt.Color(0, 153, 51));
        JBAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBAceptar.setForeground(new java.awt.Color(0, 0, 0));
        JBAceptar.setText("ACEPTAR");
        JBAceptar.setBorder(null);
        JBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAceptarActionPerformed(evt);
            }
        });

        TFNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNombreActionPerformed(evt);
            }
        });

        LabelElegir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelElegir.setForeground(new java.awt.Color(0, 0, 0));
        LabelElegir.setText("Elije el nombre de tu monstruo:");

        javax.swing.GroupLayout PanelP1Layout = new javax.swing.GroupLayout(PanelP1);
        PanelP1.setLayout(PanelP1Layout);
        PanelP1Layout.setHorizontalGroup(
            PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP1Layout.createSequentialGroup()
                .addGroup(PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelP1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(LabelDrawmon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelP1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelElegir)
                                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(134, 134, 134))
        );
        PanelP1Layout.setVerticalGroup(
            PanelP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelP1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LabelDrawmon)
                .addGap(46, 46, 46)
                .addComponent(LabelElegir)
                .addGap(18, 18, 18)
                .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBAceptarActionPerformed

    private void TFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNombreActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAceptar;
    private javax.swing.JLabel LabelDrawmon;
    private javax.swing.JLabel LabelElegir;
    private javax.swing.JPanel PanelP1;
    private javax.swing.JTextField TFNombre;
    // End of variables declaration//GEN-END:variables
}
